core/urls.py
from django.urls import path
from core import views

app_name = "core"
urlpatterns = [
    path("", views.index, name="index"),
    path("dr-gary/", views.doctor_detail, name="dr-gary"),
    path("blogs/", views.list_blogs, name="blogs"),
    path("blogs/<str:slug>/", views.blog_detail, name="blog-detail"),
    path("intake-forms/", views.list_files, name="intake-forms"),
    path("intake-forms/<str:file_id>/", views.download_pdf, name="intake-form-detail"),
    path("contact-us/", views.contact_us, name="contact-us"),
    path("ajax-contact-form", views.ajax_contact_form, name="ajax-contact-form"),
]

rebound/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from rebound.sitemaps import BlogSitemap, StaticViewSitemap
from django.contrib.sitemaps.views import sitemap
from core.views import serve_media

sitemaps = {
    "blog": BlogSitemap,
    "static": StaticViewSitemap,
}

urlpatterns = i18n_patterns(
    path("i18n/", include("django.conf.urls.i18n")),
    path("admin/", admin.site.urls),
    path("rosetta/", include("rosetta.urls")),
    path("user/", include("userauths.urls")),
    path("", include("core.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    re_path(r"^media/(?P<path>.*)$", serve_media),
    prefix_default_language=False,
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
]

core/models.py
import uuid
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
from django.conf import settings
from django.db import models
from django.template.defaultfilters import slugify

def user_directory_path(instance, filename):
    unique_filename = f"{instance.owner.id}-{filename}"
    return f"user_{instance.owner.id}/{unique_filename}"


class Blog(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True, null=True, blank=True)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="blog", null=True, blank=True, on_delete=models.SET_NULL
    )
    image = models.ImageField(upload_to=user_directory_path, blank=True, null=True)
    description = RichTextUploadingField(null=True, blank=True)
    mini_description = models.TextField(default=None, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)


    def get_absolute_url(self):
        return reverse("core:blog-detail", args=[str(self.slug)])

    def __str__(self) -> str:
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

class ContactUs(models.Model):
    full_name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    subject = models.CharField(max_length=200)
    message = models.TextField()

    def __str__(self) -> str:
        return self.full_name
    
    class Meta:
        verbose_name = "ContactUs"
        verbose_name_plural = "ContactUs"

    def __str__(self) -> str:
        return self.email

userauths/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    email = models.EmailField(unique=True, null=False)
    username = models.CharField(max_length=100)
    bio = models.CharField(max_length=100, null=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    def __str__(self) -> str:
        return self.email

core/views.py
import mimetypes
import os
from django.shortcuts import render
from core.models import Blog, ContactUs
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse, HttpResponse, Http404
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.conf import settings

# Create your views here.
def index(request):
    return render(request, "core/index.html")


def doctor_detail(request):
    return render(request, "core/dr-gary.html")

def list_blogs(request):
    list_blogs = Blog.objects.filter(is_active=True).order_by("-created_at")
    total_blogs  = list_blogs.count()
    page = request.GET.get("page", 1)
    paginator = Paginator(list_blogs, 3)
    try:
        blogs = paginator.page(page)
    except EmptyPage:
        blogs = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        blogs = paginator.page(1)
    context = {
        "blogs": blogs,
        "total_blogs": total_blogs,
    }
    return render(request, "core/list_blogs.html", context)

def blog_detail(request, slug):
    blog = Blog.objects.filter(slug=slug, is_active=True).first()
    return render(request, "core/blog-detail.html", {"blog": blog})

def contact_us(request):
    return render(request, "core/contact_us.html")

def ajax_contact_form(request):
    full_name = request.GET.get("full_name")
    email = request.GET.get("email")
    phone = request.GET.get("phone")
    subject = request.GET.get("subject") or "Make An Appointment"
    message = request.GET.get("message")
    
    from_email = settings.DEFAULT_FROM_EMAIL
    contact, _ = ContactUs.objects.get_or_create(full_name=full_name, email=email, phone=phone, subject=subject, message=message)
    context = {
        "full_name": full_name,
        "email": email,
        "phone": phone,
        "subject": subject,
        "message": message
    }
    email_template = "emails/contact_email_template.html"
    message = render_to_string(email_template, context)
    to_email = settings.ADMIN_EMAIL
    mail = EmailMessage(subject, message, from_email, to=[to_email])
    mail.send()
    
    return JsonResponse({
        "success": True,
        "message": " Message sent successfully."
    })


def list_files(request):
    pdf_files = [
        {
            "id": "AutoInjuryForm",
            "name": "AutoInjuryForm",
            "filename": "Auto Injury Form.pdf"
        },
        {
            "id": "NewPatientForm",
            "name": "NewPatientForm",
            "filename": "New Patient Form.pdf"
        },
        {
            "id": "WorkInjuryForm",
            "name": "WorkInjuryForm",
            "filename": "Work Injury Form.pdf"
        }
    ]
    return render(request, "core/list_files.html", {"pdf_files": pdf_files})


def download_pdf(request, file_id):
    # Map ID to file name
    file_mapping = {
        "AutoInjuryForm": "AutoInjuryForm.pdf",
        "NewPatientForm": "NewPatientForm.pdf",
        "WorkInjuryForm": "WorkInjuryForm.pdf"
    }

    # Check if file_id is valid
    if file_id not in file_mapping:
        raise Http404("File does not exist")

    # Path to file
    file_path = os.path.join(f"{settings.STATIC_ROOT}/assets/images/pdfs", file_mapping[file_id])

    # Check if file exists
    if not os.path.exists(file_path):
        raise Http404("File does not exist")

    # Open the file and create a response to download
    with open(file_path, "rb") as file:
        # Determine MIME type
        content_type, encoding = mimetypes.guess_type(file_path)
        if content_type is None:
            content_type = "application/octet-stream"

        # Create response
        response = HttpResponse(file.read(), content_type=content_type)
        response["Content-Disposition"] = f'attachment; filename="{file_mapping[file_id]}"'

        return response

def serve_media(request, path):
    # Specify the full path of the file
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    
    # Check if file exists
    if not os.path.exists(file_path):
        raise Http404("Media file not found")
    
    # Determine content type
    content_type, encoding = mimetypes.guess_type(file_path)
    content_type = content_type or "application/octet-stream"
    
    # Read file and return response
    with open(file_path, "rb") as f:
        response = HttpResponse(f.read(), content_type=content_type)
        if encoding:
            response["Content-Encoding"] = encoding
        return response

userauths/views.py
from django.shortcuts import render

# Create your views here.

templates/core/blog-detail.html
{% extends 'partials/base.html' %}
{% load static %}
{% load i18n %}
{% block meta_header %}
    {% if blog %}
        <title>{{ blog.title }}</title>
        <meta property="og:title" content="{{ blog.title }}" />
        <meta name="og:description"content="{{ blog.mini_description }}">
        <meta property="og:url" content="{% url 'core:blog-detail' blog.slug %}" />
        <meta property="og:image" content="{{ blog.image.url }}" />
    {% endif %}
    
{% endblock meta_header %}
{% block content %}
<!-- Start Page Banner -->
<div class="page-banner-area">
    <div class="container">
        <div class="page-banner-content">
            <h2>Blog Details</h2>
            
            <ul class="pages-list">
                <li><a href="{% url 'core:index' %}">Home</a></li>
                <li>Blog Details</li>
            </ul>
        </div>
    </div>
</div>
<!-- End Page Banner -->

<!-- Start Blog Details Area -->
<section class="blog-details-area ptb-100">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                {% if blog %}
                <div class="blog-details-desc">
                    <div class="article-image">
                        <img src="{{ blog.image.url }}" alt="image">

                        <div class="tag">{{ blog.created_at|date:"d M" }}</div>
                    </div>
                    <div class="article-content">
                        <h3>{{ blog.title }}</h3>
                        <p>{{ blog.description|safe }}</p>

                        <div class="article-tag">
                            <span>Share:</span>
                            <a href="https://www.facebook.com/" target="_blank"><i class='bx bxl-facebook'></i></a>
                            <a href="https://twitter.com/?lang=en" target="_blank"><i class='bx bxl-twitter'></i></a>
                            <a href="https://www.linkedin.com/" target="_blank"><i class='bx bxl-linkedin'></i></a>
                            <a href="https://www.instagram.com/" target="_blank"><i class='bx bxl-instagram'></i></a>
                        </div>
                    </div>
                </div>
                {% else %}
                <h3 class="text-center">Blog not found</h3>
                {% endif %}
            </div>
        </div>
    </div>
</section>
<!-- End Blog Details Area -->
{% endblock content %}

templates/core/contact_us.html
{% extends 'partials/base.html' %}
{% load static %}
{% load i18n %}
{% block meta_header %}
    <title>Contact Us</title>
    <meta property="og:title"
          content="Contact Us" />
    <meta name="og:description"
          content="Rebound Sports Medicine in Kent, WA provides expert chiropractic care and rehabilitation for sports injuries, auto accidents, and more. Dr. Gary Blackburn and his team focus on improving your overall wellness through personalized care. Whether you’re recovering from an injury or seeking pain r">
    <meta property="og:url" content="{% url 'core:contact-us' %}" />
    <meta property="og:image"
          content="{% static 'assets/images/rebound_master_logo.png' %}" />
{% endblock meta_header %}
{% block content %}
<!-- Start Page Banner -->
<div class="page-banner-area">
    <div class="container">
        <div class="page-banner-content">
            <h2>Contact Us</h2>
            
            <ul class="pages-list">
                <li><a href="{% url 'core:index' %}">Home</a></li>
                <li>Contact Us</li>
            </ul>
        </div>
    </div>
</div>
<!-- End Page Banner -->

<!-- Start Contact Area -->
<section class="contact-area ptb-100">
    <div class="container">
        <div class="section-title">
            <span class="sub-title">
                <i class="flaticon-hashtag-symbol"></i>
                Message Us
            </span>
            <h2>Drop Us Message for Any Query</h2>
            <p>Have a question? Let’s connect—drop us a message</p>
        </div>

        <div class="contact-form">
            <form method="POST" id="contact-form-ajax" action="">
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <div class="form-group">
                            <input type="text" name="full_name" id="full_name" class="form-control" required="" data-error="Please enter your name" placeholder="Name">
                            <div class="help-block with-errors"></div>
                        </div>
                    </div>

                    <div class="col-lg-6 col-md-6">
                        <div class="form-group">
                            <input type="email" name="email" id="email" class="form-control" required="" data-error="Please enter your email" placeholder="Email">
                            <div class="help-block with-errors"></div>
                        </div>
                    </div>

                    <div class="col-lg-6 col-md-6">
                        <div class="form-group">
                            <input type="text" name="phone" id="phone" required="" data-error="Please enter your number" class="form-control" placeholder="Phone">
                            <div class="help-block with-errors"></div>
                        </div>
                    </div>

                    <div class="col-lg-6 col-md-6">
                        <div class="form-group">
                            <input type="text" name="subject" id="subject" class="form-control" required="" data-error="Please enter your subject" placeholder="Subject">
                            <div class="help-block with-errors"></div>
                        </div>
                    </div>

                    <div class="col-lg-12 col-md-12">
                        <div class="form-group">
                            <textarea name="message" class="form-control" id="message" cols="30" rows="5" required="" data-error="Write your message" placeholder="Your Message"></textarea>
                            <div class="help-block with-errors"></div>
                        </div>
                    </div>

                    <div class="col-lg-12 col-md-12">
                        <button type="submit" class="default-btn">Send Message</button>
                        <div id="msgSubmit" class="h3 text-center hidden"></div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </form>
        </div>

        <div class="contact-info">
            <div class="contact-info-content">
                <h3>Contact Us by Phone Number or Email Address</h3>
                <h2>
                    <a href="tel:+0881306298615">253.854.8880</a>
                    <span>OR</span>
                    <a href="mailto:admin@reboundsportsmed.com">admin@reboundsportsmed.com</a>
                </h2>

                <ul class="social">
                    <li>
                        <a href="https://www.facebook.com/ReboundSportsMed/" target="_blank">
                            <i class='bx bxl-facebook'></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.instagram.com/rebound_sportsmed/" target="_blank">
                            <i class='bx bxl-instagram'></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>
<!-- End Contact Area -->
{% endblock content %}

templates/core/dr-gary.html
{% extends 'partials/base.html' %}
{% load static %}
{% load i18n %}
{% block meta_header %}
    <title>Chiropractic Care & Injury Rehabilitation in Kent, WA - Rebound Sports Medicine</title>
    <meta property="og:title"
          content="Chiropractic Care & Injury Rehabilitation in Kent, WA - Rebound Sports Medicine" />
    <meta name="og:description"
          content="Rebound Sports Medicine in Kent, WA provides expert chiropractic care and rehabilitation for sports injuries, auto accidents, and more. Dr. Gary Blackburn and his team focus on improving your overall wellness through personalized care. Whether you’re recovering from an injury or seeking pain r">
    <meta property="og:url" content="{% url 'core:index' %}" />
    <meta property="og:image"
          content="{% static 'assets/images/rebound_master_logo.png' %}" />
{% endblock meta_header %}
{% block content %}
<!-- Start Page Banner -->
<div class="page-banner-area">
    <div class="container">
        <div class="page-banner-content">
            <h2>Doctor Details</h2>
            
            <ul class="pages-list">
                <li><a href="{% url 'core:index' %}">Home</a></li>
                <li>Doctor Details</li>
            </ul>
        </div>
    </div>
</div>
<!-- End Page Banner -->

<!-- Start Dentist Details Area -->
<section class="dentist-details-area ptb-100">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-12 col-md-12">
                <div class="dentist-details-image text-center">
                    <img src="{% static 'assets/images/doctor/doctor-1.jpg' %}" alt="image">
                    <h1 style="color: #82b440; margin-top: 30px;">Gary Blackburn, DC FACFN</h1>
                </div>
            </div>
        </div>

        <div class="dentist-details-overview-content">
            <p><strong>Dr. Gary Blackburn, DC FACFN</strong> is a seasoned chiropractor and functional neurologist with over 30 years of experience in sports medicine, clinical neuroscience, and brain-based rehabilitation. As the founder of Rebound SportsMed, established in 2007, Dr. Blackburn is dedicated to enhancing patients’ quality of life and optimizing brain and body function through personalized, advanced care.</p>

            <p><strong>A Passionate Legacy in Clinical Neuroscience and Concussion Rehabilitation</strong></p>

            <p>Dr. Blackburn first pursued his interest in concussion management and performance enhancement as an Army Medic in 1986. This early dedication to patient care set the foundation for decades of continued study and practice in sports medicine, concussion rehabilitation, and applied functional neurology. Dr. Blackburn’s extensive post-doctoral work includes certifications in Clinical Neurosciences (2020) and as a Fellow of the American College of Functional Neurology (2022). With over 3,000 hours of continuing education since he began his practice in 1995, Dr. Blackburn exemplifies a commitment to lifelong learning.</p>

            <p><strong>Professional Background and Specialized Training</strong></p>

            <p>Dr. Blackburn trained in clinical neuroscience and functional neurology at the renowned Carrick Institute, with a focus on Vestibular Rehabilitation, Advanced Eye Movements, and Traumatic Brain Injury (TBI). His expertise is reflected in his numerous credentials, including:</p>

            <p>
                <ul>
                    <li>Diplomate of Occupational Health and Applied Ergonomics (DACBOH)</li>
                    <li>Diplomate of the American Chiropractic Rehabilitation Board (DACRB)</li>
                    <li>Certified Chiropractic Sports and Extremity Practitioner (CCSP-CCEP)</li>
                    <li>NSCA Certified Strength and Conditioning Specialist (CSCS)</li>
                    <li>Fellow of Applied Functional Sciences (FAFS), Gray Institute Certified in Applied Functional Sciences (CAFS)</li>
                </ul>
            </p>

            <p>With more than 3,000 hours of advanced training, Dr. Blackburn has specialized in areas such as Functional Range Conditioning (FRCms), Functional Manual Reaction (FMR), and Functional Systems Assessment (FRA) to provide expert, patient-centered care.</p>

            <p><strong>High-Performance Sports Consulting</strong></p>

            <p>Dr. Blackburn has a rich history in sports chiropractic, having served as an Official Team Chiropractor for the Detroit Lions (2002-2007) and as a consultant for the Detroit Tigers (2006) before relocating to the Seattle area. He also completed a prestigious sports medicine rotation with the United States Olympic Committee during the 2012 London Games, optimizing athlete care at the Chula Vista training facility.</p>

            <p><strong>Patient-Centered Approach and Recognition</strong></p>

            <p>Dr. Blackburn is known for his compassionate approach, providing each patient with individualized care that combines functional neurology, rehabilitation, and strength conditioning. His dedication has earned him multiple awards, including:</p>

            <p>
                <ul>
                    <li>3 time "Best of Kent" Winner</li>
                    <li>3 time Seattle Met “Top Doc”</li>
                </ul>
            </p>

            <p>Dr. Blackburn and Rebound SportsMed are committed to advancing patient care by integrating the latest in clinical neuroscience with a holistic, personalized approach to recovery and performance.</p>
        </div>
    </div>
</section>
<!-- End Dentist Details Area -->
{% endblock content %}

templates/core/list_blogs.html
{% extends 'partials/base.html' %}
{% load static %}
{% load i18n %}
{% block meta_header %}
    <title>Rebound SportsMed - Blogs</title>
    <meta property="og:title"
          content="Rebound SportsMed - Blogs" />
    <meta name="og:description"
          content="Rebound Sports Medicine in Kent, WA provides expert chiropractic care and rehabilitation for sports injuries, auto accidents, and more. Dr. Gary Blackburn and his team focus on improving your overall wellness through personalized care. Whether you’re recovering from an injury or seeking pain r">
    <meta property="og:url" content="{% url 'core:blogs' %}" />
    <meta property="og:image"
          content="{% static 'assets/images/rebound_master_logo.png' %}" />
{% endblock meta_header %}
{% block content %}
<!-- Start Page Banner -->
<div class="page-banner-area">
    <div class="container">
        <div class="page-banner-content">
            <h2>Blogs</h2>
            
            <ul class="pages-list">
                <li><a href="{% url 'core:index' %}">Home</a></li>
                <li>Blogs</li>
            </ul>
        </div>
    </div>
</div>
<!-- End Page Banner -->

<!-- Start Blog Area -->
<section class="blog-area pt-100 pb-100">
    <div class="container">
        <div class="section-title">
            <span class="sub-title">
                <i class="flaticon-hashtag-symbol"></i>
                Update News and Blogs
            </span>
            <h2>Stay Updated with Our Latest News and Blog</h2>
        </div>

        {% if blogs %}
        <div class="row">
            {% for blog in blogs  %}
                <div class="col-lg-4 col-md-6">
                    <div class="single-blog">
                        <div class="blog-image">
                            <a href="{% url 'core:blog-detail' blog.slug %}"><img src="{{ blog.image.url }}" style="height: 280px;" alt="image"></a>

                            <div class="tag">{{ blog.created_at|date:"d M" }}</div>
                        </div>
                        <div class="blog-content">
                            <div class="child_blog_content">
                                <h3>
                                    <a href="{% url 'core:blog-detail' blog.slug %}">{{ blog.title|truncatewords:80 }}</a>
                                </h3>
                                <p style="height: 110px;">{{ blog.mini_description|truncatewords:30 }}</p>
                            </div>
                            <!-- <a href="{% url 'core:blog-detail' blog.slug %}" class="blog-btn">Read More</a> -->

                            <ul class="entry-meta">
                                <li>
                                    <i class='bx bxs-user'></i>
                                    <span>By Administrator</span>
                                </li>
                                <li style="float: right;">
                                    <a href="{% url 'core:blog-detail' blog.slug %}" class="blog-btn">Read More</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}

            {% if total_blogs > 3 %}
                <div class="col-lg-12 col-md-12">
                    <div class="pagination-area">
                        {% if blogs.has_previous %}
                            <a href="?page={{ blogs.previous_page_number }}" class="prev page-numbers">
                                <i class='flaticon-left-arrow'></i>
                            </a>
                        {% endif %}
                        {% for num in blogs.paginator.page_range %}
                            {% if blogs.number == num %}
                                <span class="page-numbers current" aria-current="page">{{ num }}</span>
                            {% elif num > blogs.number|add:'-3' and num < blogs.number|add:'3' %}
                                <a href="?page={{ num }}" class="page-numbers">{{ num }}</a>
                            {% endif %}
                        {% endfor %}
                        {% if blogs.has_next %}
                            <a href="?page={{ blogs.next_page_number }}" class="next page-numbers">
                                <i class='flaticon-right-arrow'></i>
                            </a>
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        </div>
        {% endif %}
    </div>
</section>
<!-- End Blog Area -->
{% endblock content %}

templates/core/list_files.html
{% extends 'partials/base.html' %}
{% load static %}
{% load i18n %}
{% block meta_header %}
    <title>Rebound SportsMed - Intake Forms</title>
    <meta property="og:title"
          content="Rebound SportsMed - Download Files" />
    <meta name="og:description"
          content="Rebound Sports Medicine in Kent, WA provides expert chiropractic care and rehabilitation for sports injuries, auto accidents, and more. Dr. Gary Blackburn and his team focus on improving your overall wellness through personalized care. Whether you’re recovering from an injury or seeking pain r">
    <meta property="og:url" content="{% url 'core:intake-forms' %}" />
    <meta property="og:image"
          content="{% static 'assets/images/rebound_master_logo.png' %}" />\
{% endblock meta_header %}
{% block content %}
<!-- Start Page Banner -->
<div class="page-banner-area">
    <div class="container">
        <div class="page-banner-content">
            <h2>Intake Forms</h2>
            
            <ul class="pages-list">
                <li><a href="{% url 'core:index' %}">Home</a></li>
                <li>Intake Forms</li>
            </ul>
        </div>
    </div>
</div>
<!-- End Page Banner -->

<!-- Start Gallery Area -->
<section class="gallery-area pt-100 pb-100">
    <div class="container">
        <div class="section-title">
            <span class="sub-title">
                <i class="flaticon-hashtag-symbol"></i>
                Our Intake Form
            </span>
            <p><h2>Patient Intake Form</h2></p>
            <p>To ensure we provide you with the best care possible, please complete the appropriate intake form(s) before your appointment and bring them with you to the clinic. These forms help us understand your medical history, current condition, and any necessary details related to your visit.</p>
            <p>If you have any questions or need assistance filling out these forms, please contact our office before your appointment. We look forward to helping you on your path to recovery!</p>
        </div>

        <div class="row">
            {% for pdf in pdf_files %}
            <div class="col-lg-4 col-md-6">
                <div class="single-gallery">
                    <img src="{% static 'assets/images/gallery/gallery-1.jpg' %}" alt="image">

                    <div class="content">
                        <h3>
                            <a href="{% url 'core:intake-form-detail' pdf.id %}">{{ pdf.name }}</a>
                            <a href="{% url 'core:intake-form-detail' pdf.id %}" style="float: right;"><img src="{% static 'assets/images/download_document.png' %}" alt="image" style="width: 36px;"></a>
                        </h3>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- End Gallery Area -->
{% endblock content %}

templates/error.html
{% extends 'partials/base.html' %}
{% load static %}
{% load i18n %}
{% block meta_header %}
    <title>404 Not Found</title>
    <meta property="og:title"
          content="404 Not Found" />
    <meta name="og:description"
          content="Rebound Sports Medicine in Kent, WA provides expert chiropractic care and rehabilitation for sports injuries, auto accidents, and more. Dr. Gary Blackburn and his team focus on improving your overall wellness through personalized care. Whether you’re recovering from an injury or seeking pain r">
    <meta property="og:url" content="{% url 'core:contact-us' %}" />
    <meta property="og:image"
          content="http://static1.squarespace.com/static/63370133e12a533239738459/t/6712b9273bd4956abe798247/1729280295185/Rebound+Master+Logo.png?format=1500w" />
{% endblock meta_header %}
{% block content %}
<!-- Start Page Banner -->
<div class="page-banner-area">
    <div class="container">
        <div class="page-banner-content">
            <h2>404 Error</h2>
            
            <ul class="pages-list">
                <li><a href="{% url 'core:index' %}">Home</a></li>
                <li>404 Error</li>
            </ul>
        </div>
    </div>
</div>
<!-- End Page Banner -->

<!-- Start Error Area -->
<section class="error-area ptb-100">
    <div class="d-table">
        <div class="d-table-cell">
            <div class="container">
                <div class="error-content">
                    <img src="{% static 'assets/images/404.png' %}" alt="error">

                    <h3>Page Not Found</h3>
                    <p>The page you are looking for might have been removed had its name changed or is temporarily unavailable.</p>

                    <a href="{% url 'core:index' %}" class="default-btn">Go to Home</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Error Area -->
{% endblock content %}